# 1. Rank of Matrix

In [2]:
#Calculating the Rank of matrix

import numpy as np

# Creating a random matrix of 20x5

mat1 = np.random.random((20,5))

In [4]:
np.linalg.matrix_rank(mat1)

5

# 2. Scaling / Standardization

In [5]:
"""

X panelist:
Raw :     [0, 1, 0, 0, 1, 0, 3.46, -4.32, 2.65, -1.51]
Mean:    0.228
Standard Deviation:  2.145
Standardized:  [-0.106, 0.359, -0.106, -0.106, 0.359, -0.106,
   1.506, -2.120, 1.129, -0.810]


"""

# X Panelist

from sklearn import preprocessing
import numpy as np
XPanel = np.array([0, 1, 0, 0, 1, 0, 3.46, -4.32, 2.65, -1.51])
XPanel_scaled = preprocessing.scale(XPanel)

In [6]:
XPanel_scaled

array([-0.11203321,  0.37934052, -0.11203321, -0.11203321,  0.37934052,
       -0.11203321,  1.58811991, -2.23476775,  1.19010719, -0.85400755])

- Observation : The difference we are seeing is because standard deviation and mean values are having lesser precision.


In [7]:
XPanel.std()

2.035110807794013

In [8]:
XPanel.mean()

0.22799999999999992

# 3 . SVD

In [16]:
#Truncated SVD 

# Matrix obtained after fitting the model

import numpy as np

#creating a random matrix of 10 x 5 shape
X_large = np.random.random((10,5))

from sklearn.decomposition import TruncatedSVD

#n_components specify the number of components we want it to be reduced to
svd = TruncatedSVD(n_components=4)
svd.fit(X_large)
transformed = svd.fit_transform(X_large)

In [17]:
X_large

array([[ 0.12309039,  0.40438635,  0.04171681,  0.23789629,  0.6684614 ],
       [ 0.34467406,  0.09944487,  0.77326084,  0.87404762,  0.12463836],
       [ 0.3168184 ,  0.12917107,  0.89650242,  0.29549873,  0.23426635],
       [ 0.94627166,  0.83221747,  0.50774773,  0.75449171,  0.7983491 ],
       [ 0.03320449,  0.41704818,  0.80506678,  0.55803701,  0.13804705],
       [ 0.50399324,  0.71750692,  0.54628571,  0.48986303,  0.84387331],
       [ 0.99229751,  0.82698226,  0.59040571,  0.02780897,  0.44203844],
       [ 0.77240525,  0.42313645,  0.09373164,  0.4060426 ,  0.16525701],
       [ 0.56372366,  0.19188477,  0.59159767,  0.78954085,  0.23637471],
       [ 0.96364288,  0.32337261,  0.17486973,  0.44063615,  0.9432911 ]])

In [18]:
transformed

array([[ 0.6392525 , -0.29028622, -0.28517317, -0.32815225],
       [ 0.97913599,  0.70115836, -0.15178259,  0.18093384],
       [ 0.83123222,  0.48356471,  0.20600615, -0.10975308],
       [ 1.72623364, -0.20649761, -0.08110872,  0.01797522],
       [ 0.82944378,  0.60786963,  0.05888451, -0.26831574],
       [ 1.36839418, -0.1307954 , -0.1002523 , -0.34512978],
       [ 1.32133811, -0.34040292,  0.59208585, -0.02800332],
       [ 0.8673082 , -0.20786617,  0.08776436,  0.36899339],
       [ 1.06811118,  0.39541457, -0.12745239,  0.26525963],
       [ 1.31397501, -0.50529422, -0.25441932,  0.16840858]])

In [19]:
# Getting the U, Sigma and V Matrices 

# https://en.wikipedia.org/wiki/Singular_value_decomposition


from sklearn.utils.extmath import randomized_svd

U, Sigma, VT = randomized_svd(X_large, n_components=4)

In [20]:
U

array([[ 0.17754131, -0.21578381, -0.36628809, -0.43104776],
       [ 0.27193805,  0.52120498, -0.19495577,  0.2376675 ],
       [ 0.23086035,  0.35945707,  0.26460273, -0.14416728],
       [ 0.47943148, -0.15349968, -0.10417936,  0.02361154],
       [ 0.23036364,  0.45185894,  0.07563367, -0.3524489 ],
       [ 0.38004777, -0.09722656, -0.12876816, -0.45334876],
       [ 0.36697876, -0.25303798,  0.7604993 , -0.03678405],
       [ 0.24087982, -0.154517  ,  0.11272814,  0.48469505],
       [ 0.29664937,  0.29393081, -0.16370507,  0.3484345 ],
       [ 0.36493379, -0.37560967, -0.32678659,  0.22121482]])

In [21]:
Sigma

array([ 3.60058467,  1.34526413,  0.77854884,  0.76128978])

In [22]:
VT

array([[ 0.53066119,  0.41014215,  0.42762854,  0.42427127,  0.43279308],
       [-0.35604843, -0.25107117,  0.66405663,  0.44299179, -0.41590846],
       [ 0.31482002,  0.33222474,  0.40384206, -0.62314519, -0.48899565],
       [ 0.67361158, -0.40569293, -0.28153913,  0.30212624, -0.45947377]])

In [27]:
# Standar Singular value decomposition in SciPy module

# When we dont want to truncate 
from scipy import linalg
U, s, Vh = linalg.svd(X_large)

In [28]:
U

array([[-0.17754131,  0.21578381,  0.36628809, -0.43104776,  0.08981725,
        -0.40280285, -0.43763512, -0.118508  ,  0.01371487, -0.47526128],
       [-0.27193805, -0.52120498,  0.19495577,  0.2376675 , -0.00659115,
         0.24789589,  0.0135753 , -0.35614141, -0.49902126, -0.34980344],
       [-0.23086035, -0.35945707, -0.26460273, -0.14416728, -0.59035021,
        -0.26598248, -0.02019066,  0.52878328, -0.06688232, -0.15146812],
       [-0.47943148,  0.15349968,  0.10417936,  0.02361154,  0.30956199,
        -0.39531876,  0.66429254,  0.1218084 , -0.1547744 ,  0.05468023],
       [-0.23036364, -0.45185894, -0.07563367, -0.3524489 ,  0.29344858,
        -0.14846524, -0.30060697, -0.12456181, -0.03866713,  0.63030634],
       [-0.38004777,  0.09722656,  0.12876816, -0.45334876,  0.04855399,
         0.71962513,  0.09530711,  0.26424513,  0.14834945, -0.05357278],
       [-0.36697876,  0.25303798, -0.7604993 , -0.03678405, -0.02464044,
         0.03086244, -0.06755331, -0.43217437

In [29]:
s

array([ 3.60058467,  1.34526413,  0.77854884,  0.76128978,  0.49009283])

In [30]:
Vh

array([[-0.53066119, -0.41014215, -0.42762854, -0.42427127, -0.43279308],
       [ 0.35604843,  0.25107117, -0.66405663, -0.44299179,  0.41590846],
       [-0.31482002, -0.33222474, -0.40384206,  0.62314519,  0.48899565],
       [ 0.67361158, -0.40569293, -0.28153913,  0.30212624, -0.45947377],
       [-0.19688579,  0.70269955, -0.3658004 ,  0.37968669, -0.43529004]])

In [40]:
matrix_sample = np.array([[1000, 1, 0, 0, 1, 0, 3.46, -4.32, 2.65, -1.51],
                           [2000, 2, 0, 0, 2, 0, 7, 8,  -5, -3] ])

In [41]:
# Calculating euclidean pairwise distance matrix 

from scipy.spatial.distance import pdist
dist_matrix =  pdist(matrix_sample, 'euclidean')

In [32]:
dist_matrix

array([ 1.17374499,  1.01773072,  1.16687331,  0.98730564,  0.76940095,
        1.15350417,  0.84033014,  1.01621562,  0.92057386,  0.60298025,
        1.19897971,  0.54675339,  1.06009326,  1.34127754,  0.98497144,
        0.33038731,  1.28428025,  1.25318783,  0.49985504,  0.95562721,
        1.07318904,  0.97744472,  0.63399068,  1.22500238,  1.25261688,
        0.53137056,  0.81486393,  0.9440384 ,  0.93831946,  0.69967571,
        0.93900135,  1.22781809,  1.03744648,  0.66406367,  1.39062574,
        0.79204653,  0.9116195 ,  0.86067467,  0.71894134,  0.82328477,
        1.09979944,  0.9213004 ,  0.70499969,  0.81218335,  0.98607904])